# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='example',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ndata.proto\x12\x07\x65xample\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\"Q\n\x08Request1\x12\r\n\x05\x61rray\x18\x01 \x03(\x04\x12\x16\n\x0c\x64ouble_value\x18\x02 \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x03 \x01(\tH\x00\x42\x06\n\x04kind\"@\n\x04\x42\x62ox\x12\x0c\n\x04left\x18\x01 \x01(\x04\x12\x0b\n\x03top\x18\x02 \x01(\x04\x12\r\n\x05right\x18\x03 \x01(\x04\x12\x0e\n\x06\x62ottom\x18\x04 \x01(\x04\"\x95\x02\n\x08Request2\x12\t\n\x01\x62\x18\x01 \x01(\x0c\x12\x1c\n\x01\x65\x18\x02 \x01(\x0e\x32\x11.example.SomeEnum\x12#\n\x01m\x18\x03 \x03(\x0b\x32\x18.example.Request2.MEntry\x12!\n\x03\x61ny\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\x12(\n\x04null\x18\x05 \x01(\x0e\x32\x1a.google.protobuf.NullValue\x12)\n\x05\x61rray\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.ListValue\x12\x19\n\x02\x62s\x18\x07 \x03(\x0b\x32\r.example.Bbox\x1a(\n\x06MEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\x18\n\x08Response\x12\x0c\n\x04text\x18\x01 \x01(\t*\\\n\x08SomeEnum\x12\r\n\tUNIVERSAL\x10\x00\x12\x07\n\x03WEB\x10\x01\x12\n\n\x06IMAGES\x10\x02\x12\t\n\x05LOCAL\x10\x03\x12\x08\n\x04NEWS\x10\x04\x12\x0c\n\x08PRODUCTS\x10\x05\x12\t\n\x05VIDEO\x10\x06\x32l\n\x06Router\x12\x30\n\x06Route1\x12\x11.example.Request1\x1a\x11.example.Response\"\x00\x12\x30\n\x06Route2\x12\x11.example.Request2\x1a\x11.example.Response\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])

_SOMEENUM = _descriptor.EnumDescriptor(
  name='SomeEnum',
  full_name='example.SomeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNIVERSAL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WEB', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMAGES', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOCAL', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NEWS', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRODUCTS', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VIDEO', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=535,
  serialized_end=627,
)
_sym_db.RegisterEnumDescriptor(_SOMEENUM)

SomeEnum = enum_type_wrapper.EnumTypeWrapper(_SOMEENUM)
UNIVERSAL = 0
WEB = 1
IMAGES = 2
LOCAL = 3
NEWS = 4
PRODUCTS = 5
VIDEO = 6



_REQUEST1 = _descriptor.Descriptor(
  name='Request1',
  full_name='example.Request1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='array', full_name='example.Request1.array', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='double_value', full_name='example.Request1.double_value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_value', full_name='example.Request1.string_value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='kind', full_name='example.Request1.kind',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=80,
  serialized_end=161,
)


_BBOX = _descriptor.Descriptor(
  name='Bbox',
  full_name='example.Bbox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='left', full_name='example.Bbox.left', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top', full_name='example.Bbox.top', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right', full_name='example.Bbox.right', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bottom', full_name='example.Bbox.bottom', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=227,
)


_REQUEST2_MENTRY = _descriptor.Descriptor(
  name='MEntry',
  full_name='example.Request2.MEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='example.Request2.MEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='example.Request2.MEntry.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=507,
)

_REQUEST2 = _descriptor.Descriptor(
  name='Request2',
  full_name='example.Request2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='b', full_name='example.Request2.b', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='e', full_name='example.Request2.e', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m', full_name='example.Request2.m', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='any', full_name='example.Request2.any', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='null', full_name='example.Request2.null', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='array', full_name='example.Request2.array', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bs', full_name='example.Request2.bs', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST2_MENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=507,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='example.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='example.Response.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=509,
  serialized_end=533,
)

_REQUEST1.oneofs_by_name['kind'].fields.append(
  _REQUEST1.fields_by_name['double_value'])
_REQUEST1.fields_by_name['double_value'].containing_oneof = _REQUEST1.oneofs_by_name['kind']
_REQUEST1.oneofs_by_name['kind'].fields.append(
  _REQUEST1.fields_by_name['string_value'])
_REQUEST1.fields_by_name['string_value'].containing_oneof = _REQUEST1.oneofs_by_name['kind']
_REQUEST2_MENTRY.containing_type = _REQUEST2
_REQUEST2.fields_by_name['e'].enum_type = _SOMEENUM
_REQUEST2.fields_by_name['m'].message_type = _REQUEST2_MENTRY
_REQUEST2.fields_by_name['any'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_REQUEST2.fields_by_name['null'].enum_type = google_dot_protobuf_dot_struct__pb2._NULLVALUE
_REQUEST2.fields_by_name['array'].message_type = google_dot_protobuf_dot_struct__pb2._LISTVALUE
_REQUEST2.fields_by_name['bs'].message_type = _BBOX
DESCRIPTOR.message_types_by_name['Request1'] = _REQUEST1
DESCRIPTOR.message_types_by_name['Bbox'] = _BBOX
DESCRIPTOR.message_types_by_name['Request2'] = _REQUEST2
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.enum_types_by_name['SomeEnum'] = _SOMEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request1 = _reflection.GeneratedProtocolMessageType('Request1', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST1,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:example.Request1)
  ))
_sym_db.RegisterMessage(Request1)

Bbox = _reflection.GeneratedProtocolMessageType('Bbox', (_message.Message,), dict(
  DESCRIPTOR = _BBOX,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:example.Bbox)
  ))
_sym_db.RegisterMessage(Bbox)

Request2 = _reflection.GeneratedProtocolMessageType('Request2', (_message.Message,), dict(

  MEntry = _reflection.GeneratedProtocolMessageType('MEntry', (_message.Message,), dict(
    DESCRIPTOR = _REQUEST2_MENTRY,
    __module__ = 'data_pb2'
    # @@protoc_insertion_point(class_scope:example.Request2.MEntry)
    ))
  ,
  DESCRIPTOR = _REQUEST2,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:example.Request2)
  ))
_sym_db.RegisterMessage(Request2)
_sym_db.RegisterMessage(Request2.MEntry)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:example.Response)
  ))
_sym_db.RegisterMessage(Response)


_REQUEST2_MENTRY._options = None

_ROUTER = _descriptor.ServiceDescriptor(
  name='Router',
  full_name='example.Router',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=629,
  serialized_end=737,
  methods=[
  _descriptor.MethodDescriptor(
    name='Route1',
    full_name='example.Router.Route1',
    index=0,
    containing_service=None,
    input_type=_REQUEST1,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Route2',
    full_name='example.Router.Route2',
    index=1,
    containing_service=None,
    input_type=_REQUEST2,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROUTER)

DESCRIPTOR.services_by_name['Router'] = _ROUTER

# @@protoc_insertion_point(module_scope)
